repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.5
  hooks:
  - id: clang-format
    files: \.c(c|pp|xx|u)?$|\.h(pp)?$
    autostage: true
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.4.3
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format
